export interface ComponentMeta {
  id: string;
  name: string;
  description: string;
  category: string;
  scripts: string[];
}

export const COMPONENTS: ComponentMeta[] = [
  {
    id: 'buttons',
    name: 'Buttons',
    description: 'Call-to-action elements with multiple variants for different purposes and emphasis levels.',
    category: 'UI',
    scripts: [],
  },
  {
    id: 'forms',
    name: 'Forms',
    description: 'Form wrapper with consistent spacing, plus input elements for collecting user data.',
    category: 'Input',
    scripts: ['/assets/js/select.js', '/assets/js/password-toggle.js', '/assets/js/dutchy-form.js', '/assets/js/dutchy-form-demo.js'],
  },
  {
    id: 'cards',
    name: 'Cards',
    description: 'Content containers with various styles for different contexts and content types.',
    category: 'Layout',
    scripts: [],
  },
  {
    id: 'badges',
    name: 'Badges & Tags',
    description: 'Small status indicators and categorization labels for content organization.',
    category: 'Display',
    scripts: ['/assets/js/badge-close.js'],
  },
  {
    id: 'alerts',
    name: 'Alerts',
    description: 'Contextual feedback messages for user actions and system states.',
    category: 'Feedback',
    scripts: ['/assets/js/badge-close.js'],
  },
  {
    id: 'emptystate',
    name: 'Empty State',
    description: 'Placeholder content for empty views with helpful actions.',
    category: 'Feedback',
    scripts: [],
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    description: 'Loading placeholder animations that mimic content layout.',
    category: 'Feedback',
    scripts: [],
  },
  {
    id: 'spinner',
    name: 'Spinner',
    description: 'Square spinning loading indicator that inherits parent text color.',
    category: 'Feedback',
    scripts: [],
  },
  {
    id: 'progress',
    name: 'Progress',
    description: 'Determinate progress bars with sizes, color variants, labels, and custom max values.',
    category: 'Feedback',
    scripts: [],
  },
  {
    id: 'stats',
    name: 'Stats',
    description: 'Statistical displays and metric cards for dashboards and overviews.',
    category: 'Display',
    scripts: [],
  },
  {
    id: 'pagination',
    name: 'Pagination',
    description: 'Navigation controls for multi-page content with various styles.',
    category: 'Navigation',
    scripts: [],
  },
  {
    id: 'accordion',
    name: 'Accordion',
    description: 'Collapsible content sections for organizing information.',
    category: 'Interactive',
    scripts: ['/assets/js/accordion.js'],
  },
  {
    id: 'tabs',
    name: 'Tabs',
    description: 'Tabbed navigation with optional scrollable overflow and closable tabs.',
    category: 'Interactive',
    scripts: ['/assets/js/tabs.js'],
  },
  {
    id: 'toasts',
    name: 'Toast Notifications',
    description: 'Temporary notification messages for user feedback and alerts.',
    category: 'Feedback',
    scripts: ['/assets/js/toast.js'],
  },
  {
    id: 'modals',
    name: 'Modal / Drawer',
    description: 'Overlay panels for focused content, forms, and confirmations.',
    category: 'Overlay',
    scripts: ['/assets/js/modal.js', '/assets/js/drawer.js'],
  },
  {
    id: 'dropdowns',
    name: 'Dropdowns',
    description: 'Expandable menus for navigation and action selection.',
    category: 'Interactive',
    scripts: ['/assets/js/dropdown.js'],
  },
  {
    id: 'datatable',
    name: 'Data Table',
    description: 'Sortable, filterable tables for displaying structured data.',
    category: 'Display',
    scripts: ['/assets/js/sortable-table.js', '/assets/js/toast.js', '/assets/js/modal.js'],
  },
  {
    id: 'stepper',
    name: 'Stepper',
    description: 'Multi-step progress indicators for forms and workflows.',
    category: 'Navigation',
    scripts: ['/assets/js/stepper.js'],
  },
  {
    id: 'tooltips',
    name: 'Tooltips',
    description: 'Contextual information popups triggered on hover.',
    category: 'Display',
    scripts: [],
  },
  {
    id: 'fileupload',
    name: 'File Upload',
    description: 'Drag-and-drop file upload zones with preview support.',
    category: 'Input',
    scripts: ['/assets/js/file-upload.js'],
  },
  {
    id: 'image',
    name: 'Image',
    description: 'Responsive images with captions, expand-to-fullscreen lightbox, gallery grids, and overlay text.',
    category: 'Display',
    scripts: ['/assets/js/image-expand.js'],
  },
  {
    id: 'breadcrumbs',
    name: 'Breadcrumbs',
    description: 'Hierarchical navigation paths showing the current page location.',
    category: 'Navigation',
    scripts: [],
  },
  {
    id: 'flex',
    name: 'Flex',
    description: 'Flexible box layout component for arranging items with direction, alignment, gap, and wrapping.',
    category: 'Layout',
    scripts: [],
  },
  {
    id: 'menu',
    name: 'Menu',
    description: 'Action lists and context menus with icons, keyboard shortcuts, and destructive variants.',
    category: 'Interactive',
    scripts: ['/assets/js/dropdown.js'],
  },
  {
    id: 'text',
    name: 'Text',
    description: 'Composable typography component with family, size, weight, tracking, leading, and color props.',
    category: 'Display',
    scripts: [],
  },
  {
    id: 'scribble',
    name: 'Scribble',
    description: 'Canvas-based drawing pad for signatures and freehand sketches with export support.',
    category: 'Input',
    scripts: ['/assets/js/scribble.js'],
  },
  {
    id: 'textarea',
    name: 'Textarea',
    description: 'Multi-line text input with resize control, character counting, and validation states.',
    category: 'Input',
    scripts: ['/assets/js/textarea.js'],
  },
];
